[versions]
kotlin = "2.3.0"
spring-framework = "7.0.2"
spring-boot = "4.0.1"
spring-boot-starter-test = "4.0.1"
spring-dependency-management = "1.1.7"
spring-shell-starter = "4.0.0-M1"
spring-ai-starter="2.0.0-M1"
openapi-gradle = "1.9.0"
flyway = "11.17.0"
postgres = "42.7.8"
springdoc-openapi = "3.0.0"
apache-commons-csv = "1.14.1"
apache-poi = "5.5.0"
junit = "6.0.1"
mockito = "5.6.0"
mockito-kotlin = "6.1.0"
jakarta-persistence = "3.2.0"
jakarta-transaction = "2.0.1"
jakarta-validation = "4.0.0-M1"
kotlinx-coroutines = "1.10.2"
hibernate = "7.1.11.Final"

[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web"}
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux"}
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-cache = { module = "org.springframework.boot:spring-boot-starter-cache" }
spring-data-jpa = { module = "org.springframework.data:spring-data-jpa", version.ref = "spring-boot" }
spring-shell-starter = { module = "org.springframework.shell:spring-shell-starter", version.ref = "spring-shell-starter" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref="spring-boot" }
spring-boot-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway", version.ref="spring-boot" }
spring-ai-starter-model-openai = { module = "org.springframework.ai:spring-ai-starter-model-openai", version.ref="spring-ai-starter" }
spring-ai-openai = { module = "org.springframework.ai:spring-ai-openai", version.ref="spring-ai-starter" }
spring-ai-starter-memory-repository-jdbc = { module = "org.springframework.ai:spring-ai-starter-model-chat-memory-repository-jdbc", version.ref="spring-ai-starter" }
spring-framework-context = { module = "org.springframework:spring-context", version.ref = "spring-framework"}
spring-framework-web = { module = "org.springframework:spring-web", version.ref = "spring-framework"}
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc-openapi" }
springdoc-openapi-starter-common = { module = "org.springdoc:springdoc-openapi-starter-common", version.ref = "springdoc-openapi" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway"}
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres" }
apache-commons-csv = { module = "org.apache.commons:commons-csv", version.ref = "apache-commons-csv" }
apache-poi = { module = "org.apache.poi:poi", version.ref = "apache-poi" }
apache-poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "apache-poi"}
jakarta-persistence-api = { module = "jakarta.persistence:jakarta.persistence-api", version.ref = "jakarta-persistence" }
jakarta-transaction-api = { module = "jakarta.transaction:jakarta.transaction-api", version.ref = "jakarta-transaction" }
jakarta-validation-api  = { module = "jakarta.validation:jakarta.validation-api", version.ref = "jakarta-validation" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
hibernate-core = { module = "org.hibernate:hibernate-core", version.ref = "hibernate" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
junit-vintageEngine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
openapi-gradle = { id = "org.springdoc.openapi-gradle-plugin", version.ref = "openapi-gradle" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }