[versions]
kotlin = "2.2.21"
spring-framework = "7.0.1"
spring-boot = "4.0.0-RC2"
spring-boot-starter-test = "4.0.0-RC2"
spring-dependency-management = "1.1.7"
spring-shell-starter = "4.0.0-M1"
openapi-gradle = "1.9.0"
flyway = "11.17.0"
postgres = "42.7.8"
springdoc-openapi = "3.0.0-RC1"
apache-commons-csv = "1.14.1"
apache-poi = "5.5.0"
junit = "6.0.1"
jakarta-persistence = "3.2.0"
jakarta-transaction = "2.0.1"


[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web"}
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux"}
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-cache = { module = "org.springframework.boot:spring-boot-starter-cache" }
spring-data-jpa = { module = "org.springframework.data:spring-data-jpa", version.ref = "spring-boot" }
spring-shell-starter = { module = "org.springframework.shell:spring-shell-starter", version.ref = "spring-shell-starter" }
spring-framework-context = { module = "org.springframework:spring-context", version.ref = "spring-framework"}
spring-framework-web = { module = "org.springframework:spring-web", version.ref = "spring-framework"}
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc-openapi" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway"}
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres" }
apache-commons-csv = { module = "org.apache.commons:commons-csv", version.ref = "apache-commons-csv" }
apache-poi = { module = "org.apache.poi:poi", version.ref = "apache-poi" }
apache-poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "apache-poi"}
jakarta-persistence-api = { module = "jakarta.persistence:jakarta.persistence-api", version.ref = "jakarta-persistence" }
jakarta-transaction-api = { module = "jakarta.transaction:jakarta.transaction-api", version.ref = "jakarta-transaction" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
openapi-gradle = { id = "org.springdoc.openapi-gradle-plugin", version.ref = "openapi-gradle" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }